# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pb/request.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pb/request.proto',
  package='pb',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10pb/request.proto\x12\x02pb\"\x1e\n\x0eGetBookInfoReq\x12\x0c\n\x04isbn\x18\x01 \x01(\t\"\xbd\x01\n\x0fGetBookInfoResp\x12\x16\n\x04info\x18\x01 \x01(\x0b\x32\x08.pb.Info\x12\x14\n\x0c\x61\x62out_author\x18\x02 \x01(\t\x12\x1a\n\x12\x62rief_introduction\x18\x03 \x01(\t\x12\x11\n\tdirectory\x18\x04 \x01(\t\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x14\n\x0cwhere_to_buy\x18\x06 \x03(\t\x12\x11\n\trecommend\x18\x07 \x03(\t\x12\x16\n\x04read\x18\x08 \x01(\x0b\x32\x08.pb.Read\"\x8a\x02\n\x04Info\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tsub_title\x18\x02 \x01(\t\x12\x0c\n\x04isbn\x18\x03 \x01(\t\x12\x12\n\ntranslator\x18\x04 \x01(\t\x12\r\n\x05image\x18\x05 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x06 \x01(\t\x12\x15\n\rorigin_author\x18\x07 \x01(\t\x12\x11\n\tpublisher\x18\x08 \x01(\t\x12\x12\n\npublish_at\x18\t \x01(\t\x12\x10\n\x08page_num\x18\n \x01(\t\x12\r\n\x05price\x18\x0b \x01(\t\x12\x0f\n\x07\x62inding\x18\x0c \x01(\t\x12\x10\n\x08producer\x18\r \x01(\t\x12\r\n\x05score\x18\x0e \x01(\t\x12\x0e\n\x06series\x18\x0f \x01(\t\":\n\x04Read\x12\x0f\n\x07reading\x18\x16 \x01(\x05\x12\x0e\n\x06readed\x18\x17 \x01(\x05\x12\x11\n\twant_read\x18\x18 \x01(\x05\x32\x41\n\x07Greeter\x12\x36\n\x0bGetBookInfo\x12\x12.pb.GetBookInfoReq\x1a\x13.pb.GetBookInfoRespb\x06proto3')
)




_GETBOOKINFOREQ = _descriptor.Descriptor(
  name='GetBookInfoReq',
  full_name='pb.GetBookInfoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='isbn', full_name='pb.GetBookInfoReq.isbn', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=54,
)


_GETBOOKINFORESP = _descriptor.Descriptor(
  name='GetBookInfoResp',
  full_name='pb.GetBookInfoResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='info', full_name='pb.GetBookInfoResp.info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='about_author', full_name='pb.GetBookInfoResp.about_author', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='brief_introduction', full_name='pb.GetBookInfoResp.brief_introduction', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='directory', full_name='pb.GetBookInfoResp.directory', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='tags', full_name='pb.GetBookInfoResp.tags', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='where_to_buy', full_name='pb.GetBookInfoResp.where_to_buy', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='recommend', full_name='pb.GetBookInfoResp.recommend', index=6,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read', full_name='pb.GetBookInfoResp.read', index=7,
      number=8, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=246,
)


_INFO = _descriptor.Descriptor(
  name='Info',
  full_name='pb.Info',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='title', full_name='pb.Info.title', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sub_title', full_name='pb.Info.sub_title', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isbn', full_name='pb.Info.isbn', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='translator', full_name='pb.Info.translator', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image', full_name='pb.Info.image', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='author', full_name='pb.Info.author', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='origin_author', full_name='pb.Info.origin_author', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publisher', full_name='pb.Info.publisher', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='publish_at', full_name='pb.Info.publish_at', index=8,
      number=9, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='page_num', full_name='pb.Info.page_num', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='price', full_name='pb.Info.price', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='binding', full_name='pb.Info.binding', index=11,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='producer', full_name='pb.Info.producer', index=12,
      number=13, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='pb.Info.score', index=13,
      number=14, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='series', full_name='pb.Info.series', index=14,
      number=15, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=515,
)


_READ = _descriptor.Descriptor(
  name='Read',
  full_name='pb.Read',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reading', full_name='pb.Read.reading', index=0,
      number=22, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='readed', full_name='pb.Read.readed', index=1,
      number=23, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='want_read', full_name='pb.Read.want_read', index=2,
      number=24, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=517,
  serialized_end=575,
)

_GETBOOKINFORESP.fields_by_name['info'].message_type = _INFO
_GETBOOKINFORESP.fields_by_name['read'].message_type = _READ
DESCRIPTOR.message_types_by_name['GetBookInfoReq'] = _GETBOOKINFOREQ
DESCRIPTOR.message_types_by_name['GetBookInfoResp'] = _GETBOOKINFORESP
DESCRIPTOR.message_types_by_name['Info'] = _INFO
DESCRIPTOR.message_types_by_name['Read'] = _READ
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetBookInfoReq = _reflection.GeneratedProtocolMessageType('GetBookInfoReq', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKINFOREQ,
  '__module__' : 'pb.request_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetBookInfoReq)
  })
_sym_db.RegisterMessage(GetBookInfoReq)

GetBookInfoResp = _reflection.GeneratedProtocolMessageType('GetBookInfoResp', (_message.Message,), {
  'DESCRIPTOR' : _GETBOOKINFORESP,
  '__module__' : 'pb.request_pb2'
  # @@protoc_insertion_point(class_scope:pb.GetBookInfoResp)
  })
_sym_db.RegisterMessage(GetBookInfoResp)

Info = _reflection.GeneratedProtocolMessageType('Info', (_message.Message,), {
  'DESCRIPTOR' : _INFO,
  '__module__' : 'pb.request_pb2'
  # @@protoc_insertion_point(class_scope:pb.Info)
  })
_sym_db.RegisterMessage(Info)

Read = _reflection.GeneratedProtocolMessageType('Read', (_message.Message,), {
  'DESCRIPTOR' : _READ,
  '__module__' : 'pb.request_pb2'
  # @@protoc_insertion_point(class_scope:pb.Read)
  })
_sym_db.RegisterMessage(Read)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='pb.Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=577,
  serialized_end=642,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetBookInfo',
    full_name='pb.Greeter.GetBookInfo',
    index=0,
    containing_service=None,
    input_type=_GETBOOKINFOREQ,
    output_type=_GETBOOKINFORESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
